[project]
name = "float-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.2",
    "plotly>=6.3.0",
    "prophet>=1.1.7",
    "pydeck>=0.9.1",
    "statsmodels>=0.14.5",
    "streamlit>=1.50.0",
]
